### ISSUE TITLE
Javascript <script> tag is not formatted

### ISSUE THREAD

**Issue by kodewu** [calumk/editorjs-codecup#2]
Hello again, thank you for your work @calumk.

Unfortunately, as far as I'm concerned, everything would be fine if the script tags were displayed correctly. 

Indeed, when I create a course, I enter code in your module and I don't put any tags, I have no problems.
The content is saved in JSON format in the database. I retrieve it with :
```javascript
<script>const fd = <?= $fd ?></script>
```

___

When I save without <script> tags, it works perfecly:

![Capture d'écran 2024-01-11 202645](https://github.com/calumk/editorjs-codecup/assets/65669857/a04e09e5-95a8-4488-9370-9ce680ab5e16)

___

If I put a <script> tag, that's it, the code goes completely haywire:

![Capture d'écran 2024-01-11 202752](https://github.com/calumk/editorjs-codecup/assets/65669857/7202f0fa-b54d-44f5-968f-a7777911d657)

___

I really don't know if such a solution is really possible with storing script tags in JSON with editorJS...

**Comment by kodewu** [comment]
The strange thing is that editorJS's native operation accepts script tags and displays them without any problems:

![image](https://github.com/calumk/editorjs-codecup/assets/65669857/cd978a8a-a69f-4731-b5ee-7442b1f6fa29)

**Comment by kodewu** [comment]
Okay, In the js code, it's possible to reformat that ?

![image](https://github.com/calumk/editorjs-codecup/assets/65669857/5efc503f-c62f-47c3-bb29-88af65df8438)

**Comment by calumk** [comment]
In my test page, it is succsessfully loading this kind of string.
(take a look at the example html file)

Its hard for me to know how you are saving this / retrieving the code, perhapse the issue is not with my plugin.

Can you share some more example of how your retrieval code is working?

<img width="688" alt="image" src="https://github.com/calumk/editorjs-codecup/assets/1183991/49f8b5e2-f080-4206-9283-e2b8cf8487fe">

**Comment by kodewu** [comment]
Hello @calumk.

I use your module to colorize, and use the syntax understanding of a code (JS/HTML...).

The first step is that I'm in course-writing mode, at which point I can do whatever I want with your great module!

The second step is to store this course at the click of a button. The entire course is then saved as JSON in my database.

The third step is to display the course by retrieving it from my database.

Here are the different pieces of code so that you can understand how I do it, and what doesn't work for me:

```php
if(!empty($_GET['id'])) {
        $afficher_cours = $DB->prepare("SELECT content ... ");
        $afficher_cours->execute(array($_GET['id']));
        $cours = $afficher_cours->fetch();
        $fd = $cours['content'];
}
```

```js
<script>
        var fd = <?= $fd ?>;
        document.getElementById('formation').innerHTML = fd;
</script>
```

```html
<div id="formation"></div>
```

___

So it's during step 2/3 that the use of <script></script> tags in the "codecup" module causes the display to become completely broken. Otherwise, everything works really well, which is a real shame.

**Comment by kodewu** [comment]
On your example above, I have the same operation. When you want to store it for later display, the display breaks.

If, in your example, I hadn't set :

```html
<script>TEST</script>
```

Everything would have been displayed correctly ^^

**Comment by calumk** [comment]
But where is your js code that loads the content?

What is $fd?

**Comment by calumk** [comment]
Oh ok I see now what $fd is 

Are you using the cup.updatecode() method?

**Comment by kodewu** [comment]
I don't use the cup.updatecode(), and I don't know what it is:

```js
const ImageTool = window.ImageTool;

var editor = new EditorJS({
    holder: 'formation',
    autofocus: true,
    readOnly: true,
    tools: {
        header: {
            class: Header,
            config: {
                placeholder: 'Enter a header',
                levels: [1, 2, 3, 4],
                defaultLevel: 1,
            },
            inlineToolbar: true,
        },
        list: {
            class: List,
            tunes: ["anyTuneName"],
            inlineToolbar: true
        },
        marker: {
            class: Marker,
        },

        image: {
            class: SimpleImage,
            inlineToolbar: true,
            config: {
                placeholder: 'Paste image URL'
            }
        },
        code: {
            // class: editorjsCodeflask,
            class: editorJsCodeCup,
            options: {
                sandbox: true,
            }
        },
        // Ajout de la configuration de la force de retour à la ligne
        paragraph: {
            class: Paragraph,
            inlineToolbar: true,
            forceEnter: true, // ajouter un retour à la ligne après chaque balise <pre> et <code>
        },

        delimiter: {
            class: Delimiter,
            inlineToolbar: true,
            toolbox: {
                title: 'Insérer une séparation horizontale',
            },
        },

        underline: Underline,

        warning: {
            class: Warning,
            inlineToolbar: true,
            shortcut: 'CMD+SHIFT+W',
            config: {
                titlePlaceholder: 'Title',
                messagePlaceholder: 'Message',
            },
        },

        quote: Quote,

        alert: {
            class: Alert,
            inlineToolbar: true,
            tunes: ["anyTuneName"],
            shortcut: 'CMD+SHIFT+A',
            config: {
                defaultType: 'primary',
                messagePlaceholder: 'Enter something',
            },
        },

        nestedchecklist: editorjsNestedChecklist,

        anyTuneName: {
            class: AlignmentBlockTune,
            config: {
                default: "left",
                blocks: {
                    header: "center"
                }
            }
        },

        linkTool: {
            class: LinkTool,
            config: {
                endpoint: 'https://www.flomirtech.fr/inc/endpoint', // Your backend endpoint for url data fetching,
                pattern: /^#/,
                target: '_self'
            }
        },

        embed: {
            class: Embed,
            inlineToolbar: false,
            config: {
                services: {
                    youtube: true,
                    coub: true
                }
            }
        },

        raw: {
            class: RawTool,
            options: {
                sandbox: true,
            },
            toolbox: {
                title: 'Insérer du code HTML brut',
            },
        },
    },
    data: fd,
    onReady: () => {
        // disableEdit();
    },
    onChange: () => {
        saved();
    },
});


/**
 * It saves the data from the editor, then it takes the data and puts it in a hidden input
 * field
 */
function saved() {
    editor.save().then((savedData) => {
        // console.log('Enregistré', savedData);
        var about = document.querySelector('input[name=cours2]');
        about.value = JSON.stringify(savedData);
        // console.log(about.value);
    })
    // .catch((error) => {
        // console.log("Echec enregistrement", error)
    // })
}


function activeEdit() {
    editor.readOnly.toggle();
    $('.codeflask__textarea').css({
        "display": "block"
    });
}



// /* It's checking if the editor is ready to work. */
// editor.isReady.then(() => {
//     console.log('Editor.js is ready to work!')
// })
// /* It's catching the error. */
// .catch((reason) => {
//     console.log(`Editor.js initialization failed because of ${reason}`)
// });
```

With this function, I retrieve my course content :

```js
function saved() {
    editor.save().then((savedData) => {
        // console.log('Enregistré', savedData);
        var about = document.querySelector('input[name=cours2]');
        about.value = JSON.stringify(savedData);
        // console.log(about.value);
    })
    // .catch((error) => {
        // console.log("Echec enregistrement", error)
    // })
}
````

=> input[name=cours2] is a hidden input.

And if I click on my "Save" buttun, it executes this :

```php
/* It's updating the content of the editor. */
    if (isset($_POST['update'])) {
        if (!empty($_POST['cours2'])) {
            /* It's decoding the content of the editor. */
            $jsonC = json_decode($_POST['cours2']);

            /* It's checking if the content of the editor is empty. */
            if (!isset($jsonC->blocks[0])) {
                $_POST['cours2'] = '{"time":1665873759387,"blocks":[{"id":"IQzcrAghZ1","type":"paragraph","data":{"text":"Le cours est vide.","alignment":"left"}}],"version":"2.25.0"}';
            } else {
                /* It's updating the content of the editor. */
                $date = date('Y-m-d H:i:s');
                $req = $DB->prepare("UPDATE formation SET contenu = ?, editor = ?, date_edition = ? WHERE id_article = ?");
                $req->execute([$_POST['cours2'], $_SESSION['id'], $date, $cours['id_article']]);
                /* It's refreshing the page. */
                header('Location: ' . $_SERVER['REQUEST_URI']);
                exit;
            }
        }
    }
```


In my "< head >" section, I've loaded the "https://cdn.jsdelivr.net/npm/@calumk/editorjs-codecup@latest" CDN.

**Comment by calumk** [comment]
Ok, the issue is probably because you are going from PHP -> HTML -> JS?

You are writing the document from PHP to HTML  
```
<script>
        var fd = <?= $fd ?>;
        document.getElementById('formation').innerHTML = fd;
</script>
<div id="formation"></div>
```

It might be that this is where the issue comes from? 

It could be that the script tag is being executed because of your use of InnerHTML?

https://www.freecodecamp.org/news/innerhtml-vs-innertext-vs-textcontent/

or it could be not being escaped  properly (if it is json format?
```
<?php
  $fd_encoded = json_encode( $fd);
  echo "<script>var data = $fd_encoded;</script>";
?>
```

I might be wrong, but I am pretty confident this issue is not related to the plugin. I am afraid this is related to how you are handling the data before it gets to the plugin.

**Comment by kodewu** [comment]
Hello @calumk,

I reanalyzed in depth a question I had been asking myself all along. When I made <script> tags outside Codecup/Codeflask, and recorded my course, it worked fine.

It hadn't occurred to me to look at the return of editorJS's autosave() function. Now I can be pretty sure that everything's working. 
here: 

![image](https://github.com/calumk/editorjs-codecup/assets/65669857/f187aa10-974b-4ee1-93e7-8fae023aa2c6)

![image](https://github.com/calumk/editorjs-codecup/assets/65669857/8d924d60-f6de-4aed-b3f1-ec5f7da5731f)

___

For each "Paragraph" object, a function automatically escapes the "<" and ">" in a text field. However, we don't see these escapes on the user side.

On the other hand, for each "Code" object, nothing is escaped.

As a result, when I save my course, there are no JSON escapes in the "Code" objects.

And now I'm pretty sure it's coming from the JS script (unless I'm mistaken):

![image](https://github.com/calumk/editorjs-codecup/assets/65669857/2ea2287f-cc86-4c4d-83d0-595a7b3ec876)

**Comment by kodewu** [comment]
I must be close to finding out, if it's at the time of the save, it's surely a small detail here :

![image](https://github.com/calumk/editorjs-codecup/assets/65669857/60cedce2-658e-46fb-aa57-b04828f183eb)

**Comment by calumk** [comment]
There is no difference i can see in the output between the official @editorjs/code repo and this one.

I am sure this issue is related to how you are saving and loading the data, and writing it to the DOM.

<img width="2056" alt="image" src="https://github.com/calumk/editorjs-codecup/assets/1183991/cf2e10aa-cb64-4c01-8b62-0b20ad65e05b">

**Comment by kodewu** [comment]
Doesn't the official repo also handle < and > escapement?
Because the Paragraph repo, for example, does.
A friend of mine is going to see for himself by simulating what I want to do.
I think the code repo must be missing an escape method.

Have you ever tried saving this type of content in json, putting it in a database, and displaying it again?

**Comment by calumk** [comment]
Yes I have a full CMS that works using this plugin

**Comment by kodewu** [comment]
All right!

I'll keep looking on my own, and with the help of my colleague, we'll investigate.
In the meantime, I'll leave this issue open, and get back to you as soon as I have any news.

**Comment by calumk** [comment]
Hey, wanted to follow up and see if you had got further 

There isn't much more I can do without directly debugging your code

**Comment by kodewu** [comment]
Hey,
Yes, thank you. In fact, my friend has started but not yet completed the tests. He'll have to in his spare time.
In the meantime, I'm waiting for an answer from him, because I'm stuck in the way I code.
Maybe I'm doing something wrong ^^

**Comment by kodewu** [comment]
Hello, I've found the solution to my problem. I really had a hard time ^^

- I've made a modification to the "code" type block :

```js
const editor = new EditorJS({
    ...
    onChange: () => {
        saved();
    },
    ...
});

function saved() {
        editor.save().then((savedData) => {
            // Escape special characters within <script> tags
            savedData.blocks.forEach((block) => {
                if (block.type === 'code') {
                    block.data.code = escapeScriptTags(block.data.code);
                }
            });
    
            var about = document.querySelector('input[name=cours2]');
            about.value = JSON.stringify(savedData);
        });
    }
    
function escapeScriptTags(code) {
    return code.replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
```
____

- In my php code, I've encoded the JSON so that it's clean with the DOM.
```php
$fd = $cours['contenu'];
$escaped_fd = json_encode($fd);
```

___

- I've changed a couple of things in the contents of the codecup.js file

Adding a function
```js
function p(e) {
    return String(e).replace(/[&<>"'`=/]/g, (function(e) {
        return d[e]
    }))
}

function unescapeHTML(e) {
    return String(e).replace(/&amp;|&lt;|&gt;|&quot;|&#39;|&#x2F;|&#x60;|&#x3D;/g, (function(match) {
        return Object.keys(d).find(key => d[key] === match);
    }));
}

// ...

// this.code = e, this.elTextarea.value = e, this.elCode.innerHTML = p(e), this.highlight(), this.setLineNumber(), setTimeout(this.runUpdate.bind(this), 1)
this.code = e, this.elTextarea.value = unescapeHTML(e), this.elCode.innerHTML = e, this.highlight(), this.setLineNumber(), setTimeout(this.runUpdate.bind(this), 1)
```

**Comment by flomirtech** [comment]
Hey @calumk, It's not normal that : 

![enregistrement-2024-01-21-154831-q81uhxmn_aEAELjOe](https://github.com/calumk/editorjs-codecup/assets/65669857/92da142a-a3ad-41b7-bedf-076a00e1828d)

Normally, if I'm in ReadOnly mode to on, I must not be able to modify the content of the "Code" property.
