### ISSUE TITLE
Possibility of writing to the Code module with ReadOnly mode enabled

### ISSUE THREAD

**Issue by kodewu** [calumk/editorjs-codecup#3]
Hello @calumk, I've a new problem.

By default, editorJS is in "readOnly" mode for my users. If an admin clicks on a button, this activates the function: editor.readOnly.toggle(); :

```html
<form method="post" onsubmit="activeEdit(event.preventDefault());">
    <input type="submit" class="btn_orange" value="Edit">
</form>
```

```js
function activeEdit() {
    editor.readOnly.toggle();
}
```

I notice that in "readOnly" mode, my text can be modified in the textarea.

Digging around, I see that in the codecup.js code, there are some functions that interest me, in particular toggleReadonlyMode().

But I have no idea how to use it.
Perhaps this would allow me, before clicking on the edit button, not to be able to write in the textarea. After clicking, to be able to write in it.

I've thought of adding a "disabled" attribute, but I've no idea how to reactivate it when editing.

So that's where I'm at.

____ 

To test if the problem is mine, I took the example code you provide in the github. I've noticed that it doesn't work properly. I need to create my articles with Readonly mode set to false, and display them with ReadOnly mode set to true.

Do you agree with me?

https://github.com/calumk/editorjs-codecup/assets/65669857/92da142a-a3ad-41b7-bedf-076a00e1828d

Normally, if I'm in ReadOnly mode to on, I must not be able to modify the content of the "Code" property. 

Thank you in advance for your opinion/help or recommendations.

**Comment by calumk** [comment]
You are correct. 
This is a mistake. Fixed in 1.0.6
