### ISSUE TITLE
select language in dropdown menu

### ISSUE THREAD

**Issue by gazievs387** [calumk/editorjs-codecup#4]
Hellow, best code plugin available, good job. But what about drop down menu to select language?

And is there any way to change highlight to another theme, dark, for example?

**Comment by calumk** [comment]
Old version had a drop down. 
new version supports ALL languages supported by https://prismjs.com/ 

Just type the name in, it will be async loaded - I felt this was easier.

**Comment by gazievs387** [comment]
Ok, thanks

**Comment by calumk** [comment]
In regard to dark theme, I don't have this currently supported 

I think there was one in codeFlask, there are bits of code left that supported it... But not exposed
