### ISSUE TITLE
Can't select language, alert appear

### ISSUE THREAD

**Issue by belankus** [calumk/editorjs-codecup#6]
I've installed codecup for editorJS using bun `` bun i @calumk/editorjs-codecup``. this is my import line:

```
import editorjsCodecup from "@calumk/editorjs-codecup";

window.EJModules = {
    editorjsCodecup,
};

```

and on my editorJS instance i write the code as below:
```
const editor = new EditorJS({

    holder: "editorjs",
    // ...
    tools: {
         // ...
        code: EJModules.editorjsCodecup,
    },
   // ...
});
```

the appearance of tune block does not have selection language. when i clicked on ``plain`` on the tune block, it triggers alert

![Screenshot from 2024-05-19 00-24-27](https://github.com/calumk/editorjs-codecup/assets/60696187/ce14a9b5-44d7-4a56-9aae-40b8c17093a3)

click on ``plain`` triggers an alert

![alert](https://github.com/calumk/editorjs-codecup/assets/60696187/79160f5a-3769-4d32-8af4-59e04f6c2574)

when i click ``OK`` it causes 502 bad gateway

![bad gateway](https://github.com/calumk/editorjs-codecup/assets/60696187/bc10ee9f-e4fb-431f-ba2e-93806380235e)

i tried to search on block tune and find nothing

![notfound](https://github.com/calumk/editorjs-codecup/assets/60696187/d9e94731-7481-4cd0-ac04-48c961f67449)

my console and networks tab is seems normal

![Screenshot from 2024-05-19 00-52-22](https://github.com/calumk/editorjs-codecup/assets/60696187/59f914d0-a9e3-47ad-b141-0a9c50edf91b)

it works fine with other tools, what things i've mistaken?

**Comment by calumk** [comment]
Hi Not sure why this is failing.

There is no longer a language select, because now a cdn is used to download the required language,

I just tested the repo and have no issues. 

`git clone https://github.com/calumk/editorjs-codecup.git`

`bun i`

`bunx serve`

look at the examples/example.html


Does the example work without bugs?

**Comment by keertyverma** [comment]
I've encountered a similar issue with the `@calumk/editorjs-codecup` npm package. 
After integrating it into my Editor.js instance, the language selector list is missing from the tune block and the web editor's styles seem to be off.

![image](https://github.com/user-attachments/assets/ae4e26ba-a770-4d42-b4f8-6be29074d23b)
![image](https://github.com/user-attachments/assets/24c8c454-3e6d-42b1-a17c-e70bce9b96a6)

I have tested the example from the repository as suggested by @calumk 
- Cloned the GitHub repository for `@calumk/editorjs-codecup`.
- Installed dependencies, built the project, and opened the `example.html` file.
- Added a new code block but there is no language selection list visisble and I can see an alert pop-up when I click on language button.

![image](https://github.com/user-attachments/assets/91d88870-051f-4fc0-a416-5789d5f514c6)

**CDN Issue** -> I cannot see the list of required languages downloaded by the CDN in my setup. It seems the CDN is not providing the necessary language files or they are not being accessed correctly.


Could you please provide guidance on how to resolve this issue or suggest any additional steps to troubleshoot it?

Also please update the demo video to include an example of Editor.js code block. This will better showcase the functionality of the plugin.

Thank you for your help!

**Comment by calumk** [comment]
Hi sorry for neglecting to update the documentation. 

You should just type the language you want into the alert box.
The languages are downloaded dynamically from the server, so if you type in "JavaScript" then it will download and use the JavaScript syntax.

Please see if this works, I will update the documentation and the video to make it clearer 

I might try to make the text entry more visually appealing than the confirm entry if that is required

**Comment by belankus** [comment]
Thank you for your response, as per my problem solved, i close this issue.

**Comment by calumk** [comment]
@keertyverma  Moved to issue #7
