### ISSUE TITLE
I've encountered a similar issue with the `@calumk/editorjs-codecup` npm package.

### ISSUE THREAD

**Issue by calumk** [calumk/editorjs-codecup#7]
I've encountered a similar issue with the `@calumk/editorjs-codecup` npm package. 
After integrating it into my Editor.js instance, the language selector list is missing from the tune block and the web editor's styles seem to be off.

![image](https://github.com/user-attachments/assets/ae4e26ba-a770-4d42-b4f8-6be29074d23b)
![image](https://github.com/user-attachments/assets/24c8c454-3e6d-42b1-a17c-e70bce9b96a6)

I have tested the example from the repository as suggested by @calumk 
- Cloned the GitHub repository for `@calumk/editorjs-codecup`.
- Installed dependencies, built the project, and opened the `example.html` file.
- Added a new code block but there is no language selection list visisble and I can see an alert pop-up when I click on language button.

![image](https://github.com/user-attachments/assets/91d88870-051f-4fc0-a416-5789d5f514c6)

**CDN Issue** -> I cannot see the list of required languages downloaded by the CDN in my setup. It seems the CDN is not providing the necessary language files or they are not being accessed correctly.

Could you please provide guidance on how to resolve this issue or suggest any additional steps to troubleshoot it?

Also please update the demo video to include an example of Editor.js code block. This will better showcase the functionality of the plugin.

Thank you for your help!

_Originally posted by @keertyverma in https://github.com/calumk/editorjs-codecup/issues/6#issuecomment-2278355486_

**Comment by calumk** [comment]
@keertyverma Please try the newest release :)

![example2](https://github.com/user-attachments/assets/e4217f40-1959-4195-b316-425a8f9fe365)

**Comment by keertyverma** [comment]
Thank you for the update! The latest changes are working well for me 😀. 
The input box for entering the language name is a good improvement and has resolved the issue with the alert pop-up. 👍

I am still encountering a styling issue with the editor in my application. However, it seems to be specific to the styles in my own app, as the example.html appears to be functioning correctly.

Please go ahead and close this issue. I will open a new improvement request to propose the language selection list feature.

Thanks again for your help!
